### ISSUE TITLE
Disconnection at random after a few days

### ISSUE THREAD

**Issue by kangooooooo** [enguerrand/child-monitor#18]
We are using this app to monitor our dog and we always have an old phone as child on its crate. However, the app cuts short after a few nights in the middle of the night.
The only option to get it working again is to relaunch the app itself on the child.
Is there a pre-defined timeout for security reasons? If so, maybe it could be me tioned in the description of the app for the next ones 😁
Thanks for having brought this app to FDroid ❤️

**Comment by enguerrand** [comment]
There is no predefined timeout. It should just keep running forever. In fact that's the way I am using it: The child device is always on.
I can only imagine that this is some battery optimization of the OS that kicks in.
I recommend to go and check these settings for the child monitor app.
If you cannot find the setting or if you suspect that the problem is caused by some vendor-specific Android adaptation, consider leaving the screen on. There is some buried setting somewhere that stops the screen saver from ever being activated if the phone is charging. (this might even be part of the developer settings, can't remember.)

**Comment by kangooooooo** [comment]
Your suggestion to keep the screen on on the child device solved it.
Thanks 👍
