### ISSUE TITLE
request: show IP in parent device discovery

### ISSUE THREAD

**Issue by juleskers** [enguerrand/child-monitor#20]
Hi, and thank you for the wonderful app. It has saved our bacon a couple of times already while traveling with our little ones.

One concern that I have is that the 'discover child on network' feature gives no info on how you are about to connect.

Right now, at home, my child phone lists 5 separate IP's:
- "vpn": internal IP via wireguard VPN (to fritzbox router) 192.168.1.201
  - The VPN is mostly for going outside, to protect my data from free hotspots, by tunneling it home.
- "mobile" public, routable IP for mobile data (sim card)
- 2x internal ipv6 "WiFi" (I am guessing once for 2.4GHz, once 5GHz?)
- 1x "WiFi", direct: 192.168.1.4

My **fear** is that the discovery feature accidentally picks mobile data, which would quickly(?) burn through my 500 Megabyte (not a typo, really 0.5 gigs) data bundle.
Also, for my very specific scenario where I have a direct local WiFi ip, as well as a VPN to the same router, the direct connection should be preferred, as it has less overhead. (I could disable the VPN when coming home, but honestly, that's a hassle, and I often forget)

The UX that I am missing is that I have no idea how I can tell which network path was discovered.

This fear could be reduced in a couple of ways, as far as I can see:

1. List the discovered IP in the discovery results. This is the most detail, but the downside is that a user needs a degree in sysadmin to understand the implications.
2. Display the "category" (WiFi, VPN, mobile) with the discovery result. Less detail, and probably better for non-sysadmins. However, given my situation has 3 distinct 'WiFi', this loses some, possibly relevant, data.
3. Document somewhere how the app chooses between multiple connections, if it finds them.

In fact, can I even tell how many paths the parent-side found? My child-phone is only listed once in the discovery results. Does this mean it was only found on one path? Or is it somehow collpasing results?

I'd be grateful for any pointers, even a hint where to look in the source code would already help (/me is a professional bjava developer)

**Comment by enguerrand** [comment]
Sorry for the slow response, this one slipped through, not sure why.

In fact the discovery feature only works on the local network. You won't be able to auto-discover a device via mobile. 
The reason I added the list of all listening interfaces to the child device is that I wanted to create awareness for the device being reachable via these interfaces. It does not mean that it is also discoverable by them.

If you want absolute control you can manually connect by typing in the ip & port instead of using the discovery.
I made it remember the last settings in a recent release which actually makes this reasonably usable if you can get the child device to have a stable ip address.

Hope this helps?

**Comment by juleskers** [comment]
Hi! No worries about the response time. It's not like I'm paying you for an SLA or anything 😄❤️

I am relieved that mobile network won't be used.
I'll think about how that can be documented in the app for other worried parents. 

Re: Absolute control: 
Definitely an option, though it wasn't practical in this particular case. The hotel WiFi kept assigning us a new IP address each day (logical that their DHCP leases are short, with their high turnover) 

Re: port:
I see a bit of asymmetry in the port: you can change it on the client side, but it seems the server-side is hard coded to 10.000? Shouldn't that be an (advanced?) setting somewhere? 
Then again, I guess the current situation already helps in case there's a router-based/NAT port mapping involved, so the current state is already very useful!

**Comment by enguerrand** [comment]
The port is not hard coded in the parent device, it just **defaults** to 10000 to save typing effort because that is the port that the child device will bind to in case it's free.
NB.: That was one my main reasons to fork the upstream project. The original code would choose a random port to bind to which effectively made it impossible to manually connect, even if you knew the child device's ip address.

The way I am using this myself is that I install a vpn app on both devices to have them in the same vpn network.
That way, I don't have to care about hotel networking details or router / nat related problems. If both devices have a working internet connection, they can talk to each other via vpn.
The vpn ensures predictable ip addresses and the child device ensures a predictable port.

One more thing to note: This app does not provide any traffic encryption or authorization or any other security measure at all.
Therefore I would strongly recommend against using it in an open network such as a hotel wifi.
I feel that concerns raised in this issue have been answered, so I'll go ahead and close this.
